# Generated by Django 5.0.7 on 2024-08-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('โลโก้', models.ImageField(blank=True, upload_to='images/')),
                ('ชื่อสถานประกอบการ', models.CharField(max_length=100)),
                ('ที่ตั้ง', models.CharField(max_length=100)),
                ('จังหวัด', models.CharField(choices=[('PHUKET', 'ภูเก็ต'), ('PANGNGA', 'พังงา'), ('KRABI', 'กระบี่'), ('RANONG', 'ระนอง'), ('TRANG', 'ตรัง'), ('CHUMPORN', 'ชุมพร'), ('SURAT', 'สุราษฎร์ธานี'), ('SATUN', 'สตูล')], default='PHUKET', max_length=50)),
                ('เบอร์ติดต่อ', models.CharField(max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
